blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/FilippoGualandi-CRIF/skills-expand-your-team-with-copilot/discussions
    about: Ask questions or discuss ideas in GitHub Discussions
